return {}
-- return {
--     "morhetz/gruvbox", -- Gruvbox plugin
--     name = "gruvbox",
--     opts = {
--         theme = "gruvbox", -- Optional: configure specific options for Gruvbox
--     },
--     config = function(_, opts)
--         vim.o.background = "dark" -- Use dark mode
--         vim.cmd("colorscheme " .. opts.theme) -- Apply the Gruvbox theme
--     end,
-- }
--
